version: "3"

services:
  plutus-dev:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ..:/workspaces:cached
    environment:
      TZ: "America/Los_Angeles"
    command: sleep infinity
